### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by woj-i** [cttobin/ggthemr#13]
Great work on this package! Could you please add licence for this repo? https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by sainathadapa** [comment]
Released under GPL-3. Check the description file: [DESCRIPTION#L11](https://github.com/cttobin/ggthemr/blob/master/DESCRIPTION#L11)

**Comment by woj-i** [comment]
Thank you for quick response! I looked only on the README and GitHub tag, so I missed the information in package.
