### ISSUE TITLE
geom_col: fill color not set

### ISSUE THREAD

**Issue by czeildi** [cttobin/ggthemr#14]
with geom_col the fill color of the bars is not set to default palette color while with geom_bar it is.

```
ggthemr('flat')
ggplot(mtcars, aes(x = mpg, y = cyl)) +
    geom_col()
```

```
ggplot(mtcars, aes(x = mpg, y = cyl)) +
    geom_bar(stat = 'identity')
```

**Comment by sainathadapa** [comment]
Thanks for finding the issue! I have pushed a commit just now, which should solve this issue.

**Comment by czeildi** [comment]
super cool, perfect now!

**Comment by czeildi** [comment]
Hi, probably similar, but I am not 100% sure: geom ribbon is a generalization of geom area, and I would expect to geom_vline behave the same as geom_hline.

**Comment by sainathadapa** [comment]
Thanks! corrected now.

**Comment by czeildi** [comment]
thanks! btw cool package, I am currently working on a custom palette + theme using ggthemr.

**Comment by sainathadapa** [comment]
I'm just maintaining the package currently. @cttobin is the author, who wrote most of the code.
