### ISSUE TITLE
How to Install this R package without Internet connection

### ISSUE THREAD

**Issue by strategist922** [cttobin/ggthemr#17]
Dear team,

        Owing to some network security issue, I cannot install this package by using following commend:
devtools::install_github('cttobin/ggthemr'),

        How can I install this package without Internet connection?

Thanks nad best regardsm
James Chang

**Comment by sainathadapa** [comment]
You can follow the instructions here : http://stackoverflow.com/questions/33179156/installing-a-package-offline-from-github
