### ISSUE TITLE
The color of the point is not changed back to default theme after i reset the theme

### ISSUE THREAD

**Issue by snowhyzhang** [cttobin/ggthemr#18]
Hello

Thanks for creating so nice package!

When I use this package, I find a problem. Here is my code:

`
ggthemr("light")

ggplot(cars, aes(x = speed, y = dist)) + geom_point()

ggthemr_reset()

ggplot(cars, aes(x = speed, y = dist)) + geom_point()
`

When I reset the theme, The background is changed to the default theme, however the point is still green which I assume the point should be changed back to black. 

Thanks!

**Comment by sainathadapa** [comment]
I pushed an update that should resolve the issue. Thanks for finding the bug!
