### ISSUE TITLE
Adjust a chosen theme

### ISSUE THREAD

**Issue by nichtleiter** [cttobin/ggthemr#19]
Hi,

first of all thanks for this great package.

I really like the different themes of ggthemr. However i would like to make further adjustments. For example I want to change the font face of the labelling from 'bold' to 'normal'.

What is the preferred way of doing those adjustments to a chosen theme?

Thanks in advance

**Comment by sainathadapa** [comment]
There is no way to change the ggthemr's built-in theme settings, other than the one specified in https://github.com/cttobin/ggthemr#tweaking-themes section. You can change other settings by adding additional `theme` statements. For e.g.:

```
library(ggplot2)
library(ggthemr)
ggthemr('fresh')

ggplot(as.data.frame(cars)) +
  geom_point(aes(speed, dist)) +
  ggtitle('Plot Title') +
  theme(plot.title = element_text(face = "plain"))
```

**Comment by sainathadapa** [comment]
I have closed the issue. Let me know if you need more clarifications.
