### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zhu1meng** [cttobin/ggthemr#21]
Thank you for your work providing a powerful tool. 
However,when I use this package ,a error as followed always occured.
ggthemr('fresh')
Error in (function (el, elname)  : 
  "axis.text.x.top" is not a valid theme element name.
So,can you tell me how to solve it
  Thank you!

**Comment by sainathadapa** [comment]
I don't get such error. Can you update your packages, mainly ggplot2 and ggthemr, and try again?

**Comment by sainathadapa** [comment]
I have closed the issue. Let me know in case if you are still facing problems after updating the packages.
