### ISSUE TITLE
Panel titles cut off when using facet_wrap()

### ISSUE THREAD

**Issue by ben519** [cttobin/ggthemr#23]
For example,

```
library(ggplot2)
library(ggthemr)

ggthemr('pale')
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, size=Petal.Length))+facet_wrap(~Species)+geom_point()
```

<img width="608" alt="screen shot 2017-10-12 at 2 33 06 pm" src="https://user-images.githubusercontent.com/723099/31512935-9d3270f4-af5a-11e7-93f2-a7ff6979d019.png">

(Awesome package! Would love to see it on CRAN)

**Comment by sainathadapa** [comment]
I changed the theme settings to bring the spacing options closer to that of theme_gray, the default theme of ggplot. This should fix your issue.
