### ISSUE TITLE
Gradient colors not properly set in legend

### ISSUE THREAD

**Issue by MathieuMarauri** [cttobin/ggthemr#26]
Hello, 

I a using your package to define my own theme and palette and I ecnountered what seems to be an issue. The legend for continuous gradient is set as it was discrete.

Here is an example code.

```
library('ggthemr')
ggthemr('dust')

ggplot(iris, aes(Sepal.Width, Sepal.Length, color = Sepal.Length)) +
  geom_point(size = 4, alpha = .6)
```

Thank you for your work,

Mathieu

**Comment by sainathadapa** [comment]
Thanks for reporting the issue. The bug should be fixed now.
