### ISSUE TITLE
New theme elements in ggplot2 3.0

### ISSUE THREAD

**Issue by daroczig** [cttobin/ggthemr#28]
Hi, first of all, thanks a lot for this package :+1: 

With the most recent version of `ggplot2` on CRAN (3.0), there are a couple of new `theme` elements:

- panel.grid
- plot.tag
- plot.tag.position

That are causing a `warning` now:

```
New theme missing the following elements: panel.grid, plot.tag, plot.tag.position 
```

Is it something you can easily fix or should I look into it and come up with a PR?

**Comment by sainathadapa** [comment]
Pushed a commit to fix the issue
