### ISSUE TITLE
Is there a release date planned for ggthemr?

### ISSUE THREAD

**Issue by SRenan** [cttobin/ggthemr#3]
Hi,

I would like to use some of the themes from `ggthemr` for a package that I plan to release on BioConductor, but of course, I cannot have dependency for packages available only  on github.

The latest commits on master and dev branches are dated from last September. So I was wondering whether you already have plans for submission to CRAN?

Best.

**Comment by cttobin** [comment]
Apologies but I haven't had much time lately to work on ggthemr. I had been working on a big upgrade that included more themes and options, but haven't worked on it for the past few months.

I would like to finish it though, so I will try to get a version of the package up on CRAN by the end of the month.

**Comment by SRenan** [comment]
Of course, I understand. I was simply trying to get a timeline. The end of the month is certainly earlier than I expect my package to be ready!

Thank you.
