### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by mkborregaard** [cttobin/ggthemr#30]
Hi, 
I love the visuals you've created here, fresh and modern. So much so that in a theming library for a completely different language, julia, I've used the colors and looks of this package (with attribution in the readme). The package is [https://github.com/mkborregaard/MakieThemes.jl](https://github.com/mkborregaard/MakieThemes.jl) , it aims to provide a wide suite of popular themes for the new julia plotting package Makie.jl, and I'd like to make a ggthemr submodule for your visuals here.

The question is, are you OK with me doing that and releasing that package under the MIT license? The MIT is a more open and permissive license than GPL-3. The reason I ask is that under the GPL-3 license terms, if just one theme I use is GPL-3, my whole package needs to be GPL-3, and in turn any downstream user's project using MakieThemes would in principle also need to be GPL-3 even if they don't use any of these themes. I.e. the GPL-3 pervades all other licenses. This is not a problem in the R ecosystem, which is essentially all GPL, but e.g. in Julia most packages are on open licenses and very few packages are GPL (for this reason), so a GPL license will lead to considerably less uptake of the functionality.

I should note that we're in the borderline of open source licensing here, as I don't port any of your source code at all! The thing I'm copying is things like colors, linewidths, gridline styles and the layout of your example - things that are all available from final plots and do not require looking at your open source code. But I still feel that it is most ethical to ask your position on this given that it is clearly your intellectual property, and I will respect the decision you make here.

Thanks.

**Comment by sainathadapa** [comment]
Interesting! I only maintain the package currently, but the original author is @cttobin. He can (and should) make the decision here.

**Comment by cttobin** [comment]
@mkborregaard No problem, I'm happy for you to use the colours/styles/anything in any way you like!

**Comment by mkborregaard** [comment]
Wonderful, thanks!
