### ISSUE TITLE
Having trouble installing

### ISSUE THREAD

**Issue by mitchhendo1** [cttobin/ggthemr#35]
When I run `devtools::install_github('cttobin/ggthemr')` I'm getting the attached output (please see picture).

Tried googling and searched everywhere, updated R and all my packages, refreshed session, can't seem to work it out.

Any advice?

Thanks.

![error](https://user-images.githubusercontent.com/26275195/63062576-cd9be600-bf3c-11e9-9cc6-9c266023c8ed.JPG)

**Comment by pawel125** [comment]
@mitchhenderson, did you fix it?

**Comment by mitchhenderson** [comment]
I just retried then and it installed no problem.

Thanks for following up.
