### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by nise** [cttobin/ggthemr#8]
> devtools::install_github('cttobin/ggthemr')
Downloading GitHub repo cttobin/ggthemr@master
from URL https://api.github.com/repos/cttobin/ggthemr/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

**Comment by sainathadapa** [comment]
You probably have this problem - https://github.com/jeroenooms/curl/issues/72.  The issue that you are facing is not related to this package.
