### ISSUE TITLE
Bug with ggplot 2.2 (dev version)

### ISSUE THREAD

**Issue by dickoa** [cttobin/ggthemr#9]
Hi,

I want to start by thanking you for the `ggthemr` R package, it is a real gem.
I wanted to know if the dev version of `ggthemr` should be compatible with the recent `ggplot2` version. When are use both dev version of `ggthemr` and `ggplot2`, I get the following error:

```r
devtools::install_github("hadley/ggplot2")
devtools::install_github("cttobin/ggthemr")

library(ggplot2)
library(ggthemr)
ggthemr(palette = "flat")

## Error in theme(line = element_line(colour = line_colour, size = line_weight,  : 
##   formal argument "strip.text" matched by multiple actual arguments
```
Thanks again

**Comment by sainathadapa** [comment]
`develop` branch of `ggthemr` has not been updated for quite sometime. `master` branch is the latest version. I haven't used `ggthemr` with the dev version of `ggplot2` yet. I will try and let you know of a fix. Expect a delay in response for the fix as I am away from my computer.

**Comment by sainathadapa** [comment]
I pushed a fix to the `master` branch. Can you try now? It worked for me. There are still few warnings with the dev version of `ggplot2`, but I think it makes sense to wait for the release of the newer version, before making further changes.

**Comment by dickoa** [comment]
Thanks a lot @sainathadapa, it works and I agree for the warnings but I think we will have a new release `ggplot2` pretty soon.
Thanks again
